//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPaasInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaseSummary
    {
        public int Id { get; set; }
        public int PolicyNo { get; set; }
        public string CustomerName { get; set; }
        public string Gender { get; set; }
        public string Ageaspersystem { get; set; }
        public string Education { get; set; }
        public string KYC { get; set; }
        public string IDProof { get; set; }
        public string AddressProof { get; set; }
        public string Photo { get; set; }
        public string EnterPincode { get; set; }
        public string City { get; set; }
        public string VSMCity { get; set; }
        public string Occupation { get; set; }
        public string MedSumAssured { get; set; }
        public string FinancialSumAssured { get; set; }
        public string PreviousPolicyMLI { get; set; }
        public string PreviousPolicyMLISumAssured { get; set; }
        public string PreviousPolicyOther { get; set; }
        public string PreviousPolicyOtherSumAssured { get; set; }
        public string DeclaredIncome { get; set; }
        public string CrifScore { get; set; }
        public string CrifIncome { get; set; }
        public string AppliedSumAssured { get; set; }
        public string Financialdocument { get; set; }
        public string TeleMERReport { get; set; }
        public string MedicalRequired { get; set; }
        public string MedicalReceived { get; set; }
        public string MedicalReportDate { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string BMI { get; set; }
        public string Smoker { get; set; }
        public string UrineCotininetest { get; set; }
        public string ECGReport { get; set; }
        public string Bloodprofile_CBCFinding { get; set; }
        public string Medicalrecommendation { get; set; }
        public string Financialrecommendation { get; set; }
        public string Finalrecommendation { get; set; }
        public string FinalDecision { get; set; }
        public string Islock { get; set; }
        public string lockby { get; set; }
        public string QCby { get; set; }
        public Nullable<System.DateTime> QCbyon { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> lastmonthsal { get; set; }
        public Nullable<int> Secondlastmonthsal { get; set; }
        public Nullable<int> Thirdlastmonthsal { get; set; }
        public Nullable<int> CustomerEligibilityOnSalary { get; set; }
        public Nullable<int> LastYrGross_AY { get; set; }
        public Nullable<int> SecondLastYrGross_AY { get; set; }
        public Nullable<int> ThirdLastYrGross_AY { get; set; }
        public Nullable<int> CustomerEligibilityOnITR { get; set; }
        public Nullable<int> LastYrForm16 { get; set; }
        public Nullable<int> SecondLastYrForm16 { get; set; }
        public Nullable<int> ThirdLastYrForm16 { get; set; }
        public Nullable<int> CustomerEligibilityOnForm16 { get; set; }
        public Nullable<int> BankStmt_LastMonthSal { get; set; }
        public Nullable<int> BankStmt_SecLastMonthSal { get; set; }
        public Nullable<int> BankStmt_ThirdLastMonthSal { get; set; }
        public Nullable<int> CustomerEligibilityOnBankStmt { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    }
}
