//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPaasInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document_Master()
        {
            this.Med_Report_Master = new HashSet<Med_Report_Master>();
            this.KYC_Verify_Master = new HashSet<KYC_Verify_Master>();
            this.Monthly_Finance_Master = new HashSet<Monthly_Finance_Master>();
            this.Yearly_Finance_Master = new HashSet<Yearly_Finance_Master>();
            this.Proposal_Master = new HashSet<Proposal_Master>();
            this.Proposal_Master1 = new HashSet<Proposal_Master>();
        }
    
        public int DocMasterID { get; set; }
        public int PolicyNo { get; set; }
        public Nullable<int> DocStatusCode { get; set; }
        public string Document_Path { get; set; }
        public string DocumentName { get; set; }
        public string DocType { get; set; }
        public string DocExtension { get; set; }
        public Nullable<int> TransID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Policy_Master Policy_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Med_Report_Master> Med_Report_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KYC_Verify_Master> KYC_Verify_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Monthly_Finance_Master> Monthly_Finance_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yearly_Finance_Master> Yearly_Finance_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proposal_Master> Proposal_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proposal_Master> Proposal_Master1 { get; set; }
    }
}
