//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPaasInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document_Master
    {
        public int DocMasterID { get; set; }
        public int PolicyNo { get; set; }
        public Nullable<int> DocStatusCode { get; set; }
        public string Document_Path { get; set; }
        public string DocumentName { get; set; }
        public string DocType { get; set; }
        public string DocExtension { get; set; }
        public Nullable<int> TransID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Policy_Master Policy_Master { get; set; }
    }
}
