//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPaasInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYC_Doc_Master
    {
        public int DocID { get; set; }
        public int PolicyNo { get; set; }
        public int DocType { get; set; }
        public string Name { get; set; }
        public string IDNumber { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Policy_Master Policy_Master { get; set; }
    }
}
