//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPaasInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class KYC_Verify_Master
    {
        public int DocID { get; set; }
        public int PolicyNo { get; set; }
        public int DocMasterID { get; set; }
        public Nullable<int> Name { get; set; }
        public Nullable<int> IDNumber { get; set; }
        public Nullable<int> City { get; set; }
        public Nullable<int> Pincode { get; set; }
        public Nullable<int> DOB { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Document_Master Document_Master { get; set; }
        public virtual Policy_Master Policy_Master { get; set; }
    }
}
