//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPaasInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_Report_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Med_Report_Master()
        {
            this.Med_Report_Details = new HashSet<Med_Report_Details>();
        }
    
        public int ReportID { get; set; }
        public int PolicyNo { get; set; }
        public int DocMasterID { get; set; }
        public string ReportType { get; set; }
        public string ReportName { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Document_Master Document_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Med_Report_Details> Med_Report_Details { get; set; }
    }
}
