//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPaasInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Med_Report_Details
    {
        public int ReportDetailsID { get; set; }
        public int ReportID { get; set; }
        public string TestName { get; set; }
        public Nullable<decimal> NumericTestValue { get; set; }
        public Nullable<decimal> RangeFrom { get; set; }
        public Nullable<decimal> RangeTill { get; set; }
        public string HealthStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string StringTestValue { get; set; }
    
        public virtual Med_Report_Master Med_Report_Master { get; set; }
        public virtual Med_Report_Master Med_Report_Master1 { get; set; }
    }
}
