//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPaasInsurance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsuranceBPaaSEntities : DbContext
    {
        public InsuranceBPaaSEntities()
            : base("name=InsuranceBPaaSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Document_Master> Document_Master { get; set; }
        public virtual DbSet<Policy_Master> Policy_Master { get; set; }
        public virtual DbSet<Type_Master> Type_Master { get; set; }
        public virtual DbSet<DocType_Master> DocType_Master { get; set; }
        public virtual DbSet<Med_Report_Master> Med_Report_Master { get; set; }
        public virtual DbSet<KYC_Verify_Master> KYC_Verify_Master { get; set; }
        public virtual DbSet<Med_Report_Details> Med_Report_Details { get; set; }
        public virtual DbSet<CaseSummary> CaseSummaries { get; set; }
        public virtual DbSet<IncomeAllowableFactor> IncomeAllowableFactors { get; set; }
        public virtual DbSet<Monthly_Finance_Master> Monthly_Finance_Master { get; set; }
        public virtual DbSet<Yearly_Finance_Master> Yearly_Finance_Master { get; set; }
        public virtual DbSet<Proposal_Master> Proposal_Master { get; set; }
    }
}
