//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPaasInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monthly_Finance_Master
    {
        public int MonthlyFinance_Id { get; set; }
        public int PolicyNo { get; set; }
        public int DocMasterID { get; set; }
        public Nullable<int> SalaryAmount { get; set; }
        public Nullable<int> CrifIncome { get; set; }
        public Nullable<int> CIBILScore { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Document_Master Document_Master { get; set; }
        public virtual Policy_Master Policy_Master { get; set; }
    }
}
