//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPaasInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proposal_Master
    {
        public int ProposalNo { get; set; }
        public int PolicyNo { get; set; }
        public int DocMasterID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string DOB { get; set; }
        public string Education { get; set; }
        public string Occupation { get; set; }
        public string Employer { get; set; }
        public Nullable<decimal> AnnualIncome { get; set; }
        public Nullable<decimal> PercentageShare { get; set; }
        public string CurrentCity { get; set; }
        public Nullable<decimal> CurrentPinCode { get; set; }
        public Nullable<decimal> MobileNo { get; set; }
        public string EmailID { get; set; }
        public string PermanentCity { get; set; }
        public string PermanentPinCode { get; set; }
        public Nullable<decimal> SumAssured { get; set; }
        public string Gender { get; set; }
        public string RelationWithProposer { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Document_Master Document_Master { get; set; }
        public virtual Document_Master Document_Master1 { get; set; }
        public virtual Policy_Master Policy_Master { get; set; }
        public virtual Policy_Master Policy_Master1 { get; set; }
    }
}
