//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPaasInsurance
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yearly_Finance_Master
    {
        public int YearlyFinance_Id { get; set; }
        public int PolicyNo { get; set; }
        public int DocMasterID { get; set; }
        public Nullable<int> coi { get; set; }
        public Nullable<int> Gross_AY { get; set; }
        public Nullable<int> Form16_AY { get; set; }
        public Nullable<int> YearFrom { get; set; }
        public Nullable<int> YearTo { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string DateRange { get; set; }
    
        public virtual Document_Master Document_Master { get; set; }
        public virtual Policy_Master Policy_Master { get; set; }
    }
}
